import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aston",
  description: "Generated by create next app",
};

const RootLayout=({ children })=> {
  return (
    <html>
      <head>
        <link rel="icon"  href="favicon.ico"></link>
      </head>
      <body>

      <div className="header-bar">
        <div className="header-image">
          
          <img src="https://www.aston.ac.uk/themes/custom/aston_university/logo.svg"/>
        </div>
      </div>
      <main>{children}</main>
      </body>
    
    </html>
  );
}


export default RootLayout;